# Generated by Django 4.0.6 on 2022-09-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='posters',
            field=models.ImageField(default=None, upload_to='posters'),
            preserve_default=False,
        ),
    ]
