# Generated by Django 4.0.6 on 2022-09-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteca', '0002_pelicula_posters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='posters',
            new_name='poster',
        ),
    ]
