# Generated by Django 4.0.6 on 2022-09-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteca', '0003_rename_posters_pelicula_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos_actores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos_directores'),
            preserve_default=False,
        ),
    ]
