# Generated by Django 4.0.6 on 2022-09-06 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
    ]
