# Generated by Django 4.0.6 on 2022-09-06 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
