# Generated by Django 4.0.6 on 2022-09-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha',
        ),
    ]
